---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: eu-central-1
  version: "1.20"
availabilityZones:
- eu-central-1a
- eu-central-b
managedNodeGroups:
- name: general
  labels:
    role: general
  instanceType: t3.micro
  minSize: 2
  maxSize: 10
  desiredCapacity: 2
  volumeSize: 20
